name: Deploy docker image

on:
  push:
    branches:
      - 'main'

jobs:

  build_docker_image:
    runs-on: ubuntu-24.04
    steps:

#     Build JAR:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests

#     Set global environment variables:
      - name: set global env
        id: global_env
        run: |
          echo "{IMAGE_NAME}={module_3}" >> ${IMAGE_NAME}
          echo "{DOCKERHUB_IMAGE_NAME}={docker.pkg.github.com/sergichakov/module_3/module_3}" >> ${DOCKERHUB_IMAGE_NAME}
#          echo "::set-output name=IMAGE_NAME::${GITHUB1_REPOSITORY#*/}"
#          echo "::set-output name=DOCKERHUB_IMAGE_NAME::docker.pkg.github.com/${GITHUB1_REPOSITORY}/${GITHUB1_REPOSITORY#*/}"
#
#     Build Docker image:
      - name: Build and tag image
        run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB1_ACTOR -p ${{secrets.GITHUB1_TOKEN}}

#     Publish image to github package repository:
      - name: Publish image
        env:
          IMAGE_NAME: $GITHUB1_REPOSITORY
        run: docker push "docker.pkg.github.com/$GITHUB1_REPOSITORY/${{ steps.global_env.outputs.IMAGE_NAME }}"

